// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/role/role.proto

package role_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleRequest) Reset() {
	*x = RoleRequest{}
	mi := &file_proto_role_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRequest) ProtoMessage() {}

func (x *RoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRequest.ProtoReflect.Descriptor instead.
func (*RoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{0}
}

func (x *RoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponse) Reset() {
	*x = RoleResponse{}
	mi := &file_proto_role_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponse) ProtoMessage() {}

func (x *RoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponse.ProtoReflect.Descriptor instead.
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{1}
}

func (x *RoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_role_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetAllRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRoleRequest) Reset() {
	*x = GetAllRoleRequest{}
	mi := &file_proto_role_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoleRequest) ProtoMessage() {}

func (x *GetAllRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoleRequest.ProtoReflect.Descriptor instead.
func (*GetAllRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{3}
}

type GetAllRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*GetRoleByIDResponse `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRoleResponse) Reset() {
	*x = GetAllRoleResponse{}
	mi := &file_proto_role_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoleResponse) ProtoMessage() {}

func (x *GetAllRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoleResponse.ProtoReflect.Descriptor instead.
func (*GetAllRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllRoleResponse) GetRoles() []*GetRoleByIDResponse {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetRoleByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleByIDRequest) Reset() {
	*x = GetRoleByIDRequest{}
	mi := &file_proto_role_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleByIDRequest) ProtoMessage() {}

func (x *GetRoleByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleByIDRequest.ProtoReflect.Descriptor instead.
func (*GetRoleByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoleByIDRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRoleByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	Users         []*User                `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleByIDResponse) Reset() {
	*x = GetRoleByIDResponse{}
	mi := &file_proto_role_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleByIDResponse) ProtoMessage() {}

func (x *GetRoleByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleByIDResponse.ProtoReflect.Descriptor instead.
func (*GetRoleByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoleByIDResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRoleByIDResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetRoleByIDResponse) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *GetRoleByIDResponse) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *GetRoleByIDResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_proto_role_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRoleRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleResponse          `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_proto_role_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRoleResponse) GetRole() *RoleResponse {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *UpdateRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_role_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_role_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_role_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_role_role_proto protoreflect.FileDescriptor

const file_proto_role_role_proto_rawDesc = "" +
	"\n" +
	"\x15proto/role/role.proto\x12\x04role\x1a\x1fgoogle/protobuf/timestamp.proto\"!\n" +
	"\vRoleRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"(\n" +
	"\fRoleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x96\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x13\n" +
	"\x11GetAllRoleRequest\"E\n" +
	"\x12GetAllRoleResponse\x12/\n" +
	"\x05roles\x18\x01 \x03(\v2\x19.role.GetRoleByIDResponseR\x05roles\"$\n" +
	"\x12GetRoleByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xcd\x01\n" +
	"\x13GetRoleByIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x127\n" +
	"\tcreate_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\x127\n" +
	"\tupdate_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bupdateAt\x12 \n" +
	"\x05users\x18\x05 \x03(\v2\n" +
	".role.UserR\x05users\"7\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"V\n" +
	"\x12UpdateRoleResponse\x12&\n" +
	"\x04role\x18\x01 \x01(\v2\x12.role.RoleResponseR\x04role\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc1\x02\n" +
	"\vRoleService\x123\n" +
	"\n" +
	"CreateRole\x12\x11.role.RoleRequest\x1a\x12.role.RoleResponse\x12?\n" +
	"\n" +
	"GetAllRole\x12\x17.role.GetAllRoleRequest\x1a\x18.role.GetAllRoleResponse\x12B\n" +
	"\vGetRoleByID\x12\x18.role.GetRoleByIDRequest\x1a\x19.role.GetRoleByIDResponse\x12?\n" +
	"\n" +
	"UpdateRole\x12\x17.role.UpdateRoleRequest\x1a\x18.role.UpdateRoleResponse\x127\n" +
	"\n" +
	"DeleteRole\x12\x13.role.DeleteRequest\x1a\x14.role.DeleteResponseB\x0eZ\f./role.protob\x06proto3"

var (
	file_proto_role_role_proto_rawDescOnce sync.Once
	file_proto_role_role_proto_rawDescData []byte
)

func file_proto_role_role_proto_rawDescGZIP() []byte {
	file_proto_role_role_proto_rawDescOnce.Do(func() {
		file_proto_role_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_role_role_proto_rawDesc), len(file_proto_role_role_proto_rawDesc)))
	})
	return file_proto_role_role_proto_rawDescData
}

var file_proto_role_role_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_role_role_proto_goTypes = []any{
	(*RoleRequest)(nil),           // 0: role.RoleRequest
	(*RoleResponse)(nil),          // 1: role.RoleResponse
	(*User)(nil),                  // 2: role.User
	(*GetAllRoleRequest)(nil),     // 3: role.GetAllRoleRequest
	(*GetAllRoleResponse)(nil),    // 4: role.GetAllRoleResponse
	(*GetRoleByIDRequest)(nil),    // 5: role.GetRoleByIDRequest
	(*GetRoleByIDResponse)(nil),   // 6: role.GetRoleByIDResponse
	(*UpdateRoleRequest)(nil),     // 7: role.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),    // 8: role.UpdateRoleResponse
	(*DeleteRequest)(nil),         // 9: role.DeleteRequest
	(*DeleteResponse)(nil),        // 10: role.DeleteResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_proto_role_role_proto_depIdxs = []int32{
	11, // 0: role.User.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: role.User.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: role.GetAllRoleResponse.roles:type_name -> role.GetRoleByIDResponse
	11, // 3: role.GetRoleByIDResponse.create_at:type_name -> google.protobuf.Timestamp
	11, // 4: role.GetRoleByIDResponse.update_at:type_name -> google.protobuf.Timestamp
	2,  // 5: role.GetRoleByIDResponse.users:type_name -> role.User
	1,  // 6: role.UpdateRoleResponse.role:type_name -> role.RoleResponse
	0,  // 7: role.RoleService.CreateRole:input_type -> role.RoleRequest
	3,  // 8: role.RoleService.GetAllRole:input_type -> role.GetAllRoleRequest
	5,  // 9: role.RoleService.GetRoleByID:input_type -> role.GetRoleByIDRequest
	7,  // 10: role.RoleService.UpdateRole:input_type -> role.UpdateRoleRequest
	9,  // 11: role.RoleService.DeleteRole:input_type -> role.DeleteRequest
	1,  // 12: role.RoleService.CreateRole:output_type -> role.RoleResponse
	4,  // 13: role.RoleService.GetAllRole:output_type -> role.GetAllRoleResponse
	6,  // 14: role.RoleService.GetRoleByID:output_type -> role.GetRoleByIDResponse
	8,  // 15: role.RoleService.UpdateRole:output_type -> role.UpdateRoleResponse
	10, // 16: role.RoleService.DeleteRole:output_type -> role.DeleteResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_role_role_proto_init() }
func file_proto_role_role_proto_init() {
	if File_proto_role_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_role_role_proto_rawDesc), len(file_proto_role_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_role_role_proto_goTypes,
		DependencyIndexes: file_proto_role_role_proto_depIdxs,
		MessageInfos:      file_proto_role_role_proto_msgTypes,
	}.Build()
	File_proto_role_role_proto = out.File
	file_proto_role_role_proto_goTypes = nil
	file_proto_role_role_proto_depIdxs = nil
}
